### ISSUE TITLE
Make it easier to find the list of predefined units?

### ISSUE THREAD

**Issue by kendonB** [edzer/units#21]
I have skimmed through blog posts, function documentation, github README, and can't find a link to this. Am I being blind?

I would suggest, at least, putting a link to this on all the function documentation pages in details.

**Comment by edzer** [comment]
It's called `ud_units`. Have you read the package vignettes?

**Comment by kendonB** [comment]
Got it, thanks! Hadn't read the vignettes - is there a nice way to print this list to see everything?

**Comment by kendonB** [comment]
I assume the original database has English descriptions of everything as well - this could be a nice addition in the R package? Something like ``describe(units_vctr)`` which would print the English description of the units.

**Comment by xhdong-umd** [comment]
The list is just a simple list of unit name. There is no description so it will not serve that purpose. I tried to build a table from the original xml database so that you can look up standard unit name, but the xml is difficult to convert especially when there are symbols in names written as unicode, like the degree symbol.

Then I tried to load the xml and run `stringr::str_view` to find unit by keyword, which has a nice htmlwidget interface to highlight the match. Turned out `str_view` cannot handle the xml string because it just added a tag to the matched keyword then built a html from it, and all xml tags become html tags and are invisible.

The easiest method to look up unit and their definitions, names now, is to just open the xml files and search by keyword. The xml is self explained, though there are 5 different xml files you need to look at them. They cannot be combined because they are of different schemas.

```
xml_path_prefix <- system.file("share", package = "udunits2")
xml_file_names <- c("udunits2-prefixes.xml", 
               "udunits2-base.xml", 
               "udunits2-derived.xml", 
               "udunits2-accepted.xml",
               "udunits2-common.xml")
xml_files <- paste0(xml_path_prefix, "/", xml_file_names)
file.edit(xml_files) 
```

Or you can open [the xml in browser](http://www.unidata.ucar.edu/software/udunits/udunits-2.2.24/doc/udunits/udunits2.html#Database):

**Comment by edzer** [comment]
PR welcome!
