### ISSUE TITLE
Could units functions automatically search ``ud_units``?

### ISSUE THREAD

**Issue by kendonB** [edzer/units#23]
For example, ``as.units(1:10, ha)`` would first look in the search path for a ``units`` object named ``ha``, then, if this fails, look in ``ud_units``.

**Comment by mailund** [comment]
@edzer I think I have an idea for how this can be done. I would just search down the environment path and look for objects of the right name and if I reach `emptyenv()` go for `ud_units`. The only issue is that for the syntax, as described, we need non-standard evaluation. It is not a major problem, but it *does* open the function up for some problems when used in programs rather than interactively. 

Anyway, if you want to assign me the issue, I'll give it a go.

**Comment by edzer** [comment]
Yes, please try - this will certainly increase usability. I gave it a short try, but couldn't figure out how to do it.

**Comment by xhdong-umd** [comment]
Sometimes I want to use a unit in udunits but I'm not sure the standard name of it (will second be `s`, `sec`, `second`, `seconds`?). If we can have a look up table for every udunits unit including name, definition, symbol, then user can simply open that data frame in RStudio, search for the unit interested. Or he can search the data frame with some keywords.

I tried to build this kind of table but stopped at some error caused by special symbols like degree. Since @mailund already have the xml read and parsed in `ud_units.R`, it should be easy to add. If you don't have time I can work on it, though I want to make sure all of you like the idea and we agree on the details of the usage.

**Comment by mailund** [comment]
I don't have time to do this within the next couple of weeks, but I think you can use the code I used for parsing the XML files to do it. It is in the ud_units.R file.
