### ISSUE TITLE
Unit conversion on Temperature not accurate

### ISSUE THREAD

**Issue by glennSanders** [edzer/units#24]
Hi.

In my below attempt to convert Temperature units below I get an inaccurate result:

```r
library(units)
Temp <- 75 * parse_unit('degF')
units(Temp) <- parse_unit('degK')
print(Temp)
# Result check with udunits2
udunits2::ud.convert(75,'degF','degK')
```
The result is:
```
> library(units)
> Temp <- 75 * parse_unit('degF')
> units(Temp) <- parse_unit('degK')
> print(Temp)
19194.58 degK
> udunits2::ud.convert(75,'degF','degK')
[1] 297.0389
```
The correct answer is 297K

I have used this method to convert units of Pressure, Length, Velocity, Time and Power seemingly without issue.

Am I doing something wrong?

Session info below:
```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] units_0.4-1

loaded via a namespace (and not attached):
[1] tools_3.3.2   udunits2_0.13 knitr_1.15.1 
```
Thanks for any assistance

**Comment by edzer** [comment]
Thanks! Embarrassingly, the current implementation assumes all conversions multiply by a constant, without an offset. I wrote a quick patch, short circuiting to directly use `ud.convert` here. Please install from github directly with `devtools::install_github("edzer/units")`.

@mailund , could you pls check whether there are other cases where your `.get_conversion_constant` logic might not work out in such cases?

**Comment by mailund** [comment]
It wouldn't work anywhere, where the conversion is not a constant. I hadn't thought about it at all. Embarrassingly, considering such simple cases as conversion from Celcius to Kelvin where the entire conversion is an offset. It is easily fixed if we can assume that all conversions are linear (y = a*x + b), since there I can figure out the offset by converting 0 to 0 and the scaling by converting 1 to 1, but as long as we don't have user-defined conversion, then using `ud.convert` is probably the easiest solution.

The `.get_conversion_constant` is not used anywhere else, so I believe this change fixes the problem.

**Comment by edzer** [comment]
Thanks. It seems that unit simplification makes similar assumptions. Is:
```
> Temp <- 75 * parse_unit('degF')
> units(Temp) <- parse_unit('degK')
> Temp / parse_unit('degF')
-136005.2 1
```
a meaningful simplificiation?

**Comment by edzer** [comment]
With https://github.com/edzer/units/commit/0a4076373393817d8362b38cf0f33d1410724b30 at least we get
```
> library(units)
> Temp <- 75 * parse_unit('degF')
> units(Temp) <- parse_unit('degK')
> Temp / parse_unit('degF')
297.0389 degK/degF
```
which should ring alarm bells for someone understanding units; however we still have
```
> parse_unit("degF") / parse_unit('degK')
1 degF/degK
> a = 10 * parse_unit('degF')
> b = 5 * parse_unit('degF')
> a/b
2 1
```
mmm, the ratio of two interval variables...

**Comment by mailund** [comment]
Right, I see there is also the same assumption in .get_unit_conversion_constant. That is used in unit simplification. Fixing that might be a little harder. There, it would be necessary to keep track of both offset and scale. I think it can be fixed in the same way, though. We just have to transform one of the values according to the units, one at a time, along the nominator and denominator in `simplify_units`. That function can't work only on symbolic units, then, but would need to know the value we are trying to convert, but it shouldn't be a problem making it do the right thing.

I have to go to a PhD defence in 15 mins, but I will look at it in the evening or tomorrow.

**Comment by mailund** [comment]
I made a PR to address this -- I had some time between the defence and the reception.

I'm essentially just doing the same fix in the unit simplification as you did in the conversion, so it only works for udunits (but, then, nothing works for user-defined units yet, so I guess that is fine).

**Comment by mailund** [comment]
Has this issue been resolved now and can be closed, or are there still problems? I plan to look a little at user-defined conversion today -- I have some ideas for it I plan to try out -- but if there are still problems here, I would like to get that solved first.
